%% General CMG

act.cmg.beta = deg2rad(40); % [1x1] - rad Inclination of the pyramid
act.cmg.quanta = 1.5e-3; % [1x1] rad - Quanta dimension for the sensor of position
act.cmg.angsat = 40; % [1x1] rad/s - Maximum angular rate that can be generated by the motor
act.cmg.sat = 9; % [1x1] Nm - Maximum torque achivable by the system